config:
  existingSecret: oauth2-proxy-creds-google

extraArgs:
  whitelist-domain: .mcmattco.com
  cookie-domain: mcmattco.com

ingress:
  enabled: true
  path: /
  hosts:
    - oauth.mcmattco.com
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: oauth2-proxy-https-cert
      hosts:
        - oauth.mcmattco.com
