apiVersion: v1
data:
  user: matt
  host: "matt-db.c0rhqqiwezsa.us-east-1.rds.amazonaws.com"
  port: "5432"
  db: beefstew
  sslmode: require
  bind: "0.0.0.0"
  listen: "8081"
kind: ConfigMap
metadata:
  name: pgstrings
  namespace: default
  resourceVersion: "8340833"
  selfLink: /api/v1/namespaces/default/configmaps/pgstrings
  uid: 5aa9b971-7513-11ea-b274-06408db1cb24
